### ISSUE TITLE
Participation in events is transmitted/displayed incorrectly, when events that were created later, occurr at an earlier date

### ISSUE THREAD

**Issue by flo-schu** [flo-schu/diverssite#51]
To reproduce: 

- create two events at date X in the future
- register participation for the events
- create another event at date Y in the future where Y takes place earlier than X

You should be able to see already a mix up in the events

**Comment by hf-kklein** [comment]
I didn't test locally but my best guess is, the problem is here:
https://github.com/flo-schu/diverssite/blob/56d16ffd43dee25627024fc184ff1b30e41f8e6d/events/views.py#L79

We're querying with a list of events and applying a filter on those events that the given user attends. The error didn't occur until now, because as long as a single user attends no more than one event from `events`, the sorting is irrelevant because the result set is eithe rempty or only holds one record.

As soon as a user attends more than 1 event, the sorting or the `participation` result set becomes unstable because, by default, SQL does not give any guarantees about any kind of implicit sorting. Only explicit sorting with ORDER BY guarantees for a stable sorting of the result set. This explains why it sometimes works, and sometimes it doesn't. If my guess is correct the data on the DB are just fine, only their processing is in the application buggy.

**Comment by flo-schu** [comment]
indeed participation was sorted accoding to the id of creation of the participation while events were sorted by date.
particiation is now a list generated during iteration of events. Therefore it will always have the same order as evens and no longer cause sorting issues
